CREATE TABLE `contact` (
  `CON_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CON_TS` datetime NOT NULL,
  `MITASRX_ID` int(3) NOT NULL,
  `CON_ANT` int(1) NOT NULL,
  `CON_FREQ` float(6,3) NOT NULL,
  `CON_CODE` int(4) NOT NULL,
  `CON_TYPE` int(2) NOT NULL,
  `CON_POWER` int(3) NOT NULL,
  PRIMARY KEY (`CON_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=25092771 DEFAULT CHARSET=utf8 PACK_KEYS=1;